export { InputTemplate } from './input'
export { ContainerTemplate } from './container'
export { TitleTemplate } from './title'
export { ButtonTemplate } from './button'
export { LinkTemplate } from './link'
export { FileInputTemplate } from './fileInput'
export { DividerTemplate } from './divider'
export { BackButtonTemplate } from './backButton'
