export { LoginPage } from './Login'
export { SignUpPage } from './SignUp'
export { ChatsPage } from './Chats'
export { ProfilePage } from './Profile'
export { ChangePasswordPage } from './ChangePassword'
export { ErrorPage } from './Error'
