export { Login } from './login/LoginPage'
export { SignUp } from './signUp/SignUpPage'
export { Chats } from './chats/ChatsPage'
export { UserProfile } from './userProfile/UserProfilePage'
export { ChangePassword } from './changePassword/ChangePasswordPage'
export { Error } from './error/ErrorPage'
